config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/faq', to: 'static_pages#faq'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  #sign up routes
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  #omniauth route
  match '/auth/:provider/callback', to: 'sessions#omniauth', via: [:get, :post]

    controller :sessions do
      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
  end

  get '/profile', to: 'users#show'
  get 'qals/finished_quilts', :to => 'qals#finished_quilts'
  get 'qals/beginners', :to => 'qals#good_for_beginners'
  get 'qals/ending_soon', :to => 'qals#ending_soon'

  resources :users, :only => [:create, :new, :show, :edit, :update]
  resources :qals 
  resources :quilts

#   nestiing new quilt form
  resources :quilters do 
    resources :quilts, :only => [:create, :index, :new]
  end

  resources :sponsors 
  resources :prizes
end

app/models/qal.rb
class Qal < ApplicationRecord

    belongs_to :user
    has_many :quilters, dependent: :destroy
    has_many :quilts, dependent: :destroy

    has_many :prizes, dependent: :destroy
    has_many :sponsors, through: :prizes

    validates :qal_name, presence: true, uniqueness: true

    accepts_nested_attributes_for :prizes
    accepts_nested_attributes_for :quilters
    accepts_nested_attributes_for :quilts


    scope :beginner, -> {where(skill_level: 'Beginner')}
    scope :ending_soon, -> { order(:end_date, :desc) }
    scope :finished_quilts, -> {includes(:quilts).where(quilts: {is_finished: true})}
end

app/controllers/qals_controller.rb
class QalsController < ApplicationController
    before_action :require_login
    
    def new
        @qal = Qal.new
    end

    def create
        @qal = current_user.qals.create(qal_params)
        if @qal.save
            redirect_to qal_path(@qal)
        else
            render :new
        end
    end

    def show
        @qal = Qal.find_by(id: params[:id])
       
    end

    def edit
        @qal = Qal.find_by(id: params[:id])
    end

    def update
        @qals = Qal.all
        @qal = Qal.find_by(id: params[:id])
        if @qal.update(qal_params)
            redirect_to qal_path
        else
            render :edit
        end
    end

    def destroy
        @qal = Qal.find(params[:id])
        @qal.destroy
        redirect_to current_user
    end

    def index
        @qals = Qal.all
        @users = User.all
    end

    def good_for_beginners
        @qals = Qal.all
        @good_for_beginners = @qals.beginner

    end

    def finished_quilts
        @qals = Qal.all
        @finished_quilts = @qals.finished_quilts
    end

    def ending_soon
        @qals = Qal.all
        @ending_soon = @qals.ending_soon
    end


    private

    def qal_params
        params.require(:qal).permit(:qal_name, :start_date, :end_date, :quilting_style, :skill_level)
    end

end

app/views/qals/_form.html.erb
<%= render partial: "layouts/errors", locals: {object: @qal} %>

<%= form_for(@qal) do |f| %>

<div>
    <%= f.label :qal_name %>
    <%= f.text_field :qal_name %>
<div>

<div>
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
</div>

<div>
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
</div>

<div>
    <%= f.label "Skill Level" %>
    <%= f.select :skill_level, options_for_select([["Beginner", 'Beginner'], ["Intermediate", 'Intermediate'], ["Advanced", 'Advanced'], ["Challenging", 'Challenging']]) %>
</div>

<div>
    <%= f.label "Quilt Style" %>
    <%= f.select :quilting_style, options_for_select([['Modern', 'Modern'], ['Traditional', 'Traditional']]) %>
</div>

<%= f.submit yield(:button_text), class: "btn btn-primary" %>

<% end %>

app/views/qals/beginners.html.erb
<p>Quilt-A-Longs that are good for beginners: <% @good_for_beginners.each do |qal|%>    </p>
    <p><%=qal.qal_name%> </p>
    <% end %> 

    <p> <%= link_to "Back to all Quilt-A-Longs", qals_path %> </p>

app/views/qals/edit.html.erb
<% provide(:title, "Edit Quilt-A-Long") %>
<% provide(:button_text, 'Edit Quilt-A-Long') %>

<h1> Edit your Quilt-A-Long </h1>


    <%= render 'form' %>

  

app/views/qals/ending_soon.html.erb
<p>Quilt-A-Longs by end date: <% @ending_soon.each do |qal|%>    </p>
    <p><%=qal.qal_name%> </p><br>
    <p><%=qal.end_date%> </p><br>

    <% end %> 

    <p class="btn btn-sm"> <%= link_to "Back to all Quilt-A-Longs", qals_path %> </p>

app/views/qals/finished_quilts.html.erb
<p>Quilt-A-Longs with finished quilts: <% @finished_quilts.each do |qal|%>    </p>
    <p><%=qal.qal_name%> </p>
    <% end %> 

    <p class="btn btn-sm"> <%= link_to "Back to all Quilt-A-Longs", qals_path %> </p>

app/views/qals/good_for_beginners.html.erb
<p>Quilt-A-Longs that are good for beginners: <% @good_for_beginners.each do |qal|%>    </p>
    <p><%=qal.qal_name%> </p>
    <% end %> 

    <p class="btn btn-sm"> <%= link_to "Back to all Quilt-A-Longs", qals_path %> </p>

app/views/qals/index.html.erb
<h1> Quilt-A-Longs </h1>

<p class="btn btn-sm"><%= link_to "Add New", new_qal_path %></p>
<p class="btn btn-sm"><%= link_to "My Profile", current_user %></p>


<p class="btn btn-sm"> <%= link_to "Quilt-A-Longs for Beginners", qals_beginners_path %> </p>
<p class="btn btn-sm"> <%= link_to "Quilt-A-Longs with finished quilts", qals_finished_quilts_path %> </p>                 
<p class="btn btn-sm"> <%= link_to "Quilt-A-Longs by ending date", qals_ending_soon_path %> </p>                 


    <table class="table">
        <thead>
            <tr>
              <th> Name </th>
              <th> Start Date </th>
              <th> End Date </th>
              <th> Skill Level </th>
              <th> Quilting Style </th>
              <tr> </tr>
        </thead>
        <tbody>
            <% @qals.each do |q| %>
            <tr>
                <td><%= link_to q.qal_name, qal_path(q) %></td>
                <td> <%= q.start_date %></td>
                <td><%= q.end_date %></td> 
                <td><%= q.skill_level %></td> 
                <td><%= q.quilting_style %></td> 

                <% if current_user.id == q.user_id %> 
                    <td> 
                        <p class="btn btn-sm"><%= link_to "Edit", edit_qal_path(q)%></p>
                        <p class="btn btn-sm"><%= link_to "Delete", qal_path(q), method: :delete, data: { confirm: "Are you sure?" }  %></p>
                    </td>
                    <% end %>
                
            </tr>
              <% end %>
        </tbody>
    </table>
   

app/views/qals/new.html.erb
<% provide(:title, "New Quilt-A-Long") %>
<% provide(:button_text, 'Add New') %>

<h1>Add a new Quilt-A-Long</h1>

<%= render 'form' %>

app/views/qals/show.html.erb
<h1><%= @qal.qal_name %></h1>

<% if current_user.id == @qal.user_id %>
    <p class="btn btn-sm"><%= link_to "Edit", edit_qal_path(@qal)%></p>
    <p class="btn btn-sm"><%= link_to "Delete", qal_path(@qal), method: :delete, data: { confirm: "Are you sure?" }  %></p>
    <% end %>

     <p class="btn btn-sm"><%= link_to "My Profile", current_user %></p>

<div>
    <p class="qal-label">Designer: <%= @qal.user.company_name%></p>
</div>

<div>
    <p class="qal-label"> Start date: <%= @qal.start_date %></p>
    <p class="qal-label"> End date: <%= @qal.end_date %></p>

    <p class="qal-label">Skill level: <%= @qal.skill_level %></p>
    <p class="qal-label">Quilt style: <%= @qal.quilting_style %></p>
</div>

<div>
    <p class="qal-label">My Quilters: <% @qal.quilters.each do |quilter| %></p>
    
        <ul>
            <li><%= link_to quilter.quilter_name, quilter_path(quilter) %></li>
            <li>Quilts: <% quilter.quilts.each do |quilt_name| %> </li>
                        <p><%= quilt_name.quilt_name %></p>
                        <% end %>
        </ul>
        <% end %><br>
       
    <p class="btn btn-sm"><%= link_to "View all Quilters", quilters_path %></p>
  


    <p class="qal-label">Prizes: <% @qal.prizes.each do |prize| %></p>
        <ul>
            <li><%= link_to prize.prize_name, prize_path(prize) %></li>
            <% if prize.sponsor %>
            <li>Sponsored by: <%= prize.sponsor.sponsor_name %></li>
                <%end%>
        </ul>
        <% end %>
        
    <p class="btn btn-sm"><%= link_to "View all Prizes", prizes_path%></p>
    
</div>