config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/faq', to: 'static_pages#faq'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  #sign up routes
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  #omniauth route
  match '/auth/:provider/callback', to: 'sessions#omniauth', via: [:get, :post]

    controller :sessions do
      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
  end

  get '/profile', to: 'users#show'
  get 'qals/finished_quilts', :to => 'qals#finished_quilts'
  get 'qals/beginners', :to => 'qals#good_for_beginners'
  get 'qals/ending_soon', :to => 'qals#ending_soon'

  resources :users, :only => [:create, :new, :show, :edit, :update]
  resources :qals 
  resources :quilts

#   nestiing new quilt form
  resources :quilters do 
    resources :quilts, :only => [:create, :index, :new]
  end

  resources :sponsors 
  resources :prizes
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true

    has_many :qals, dependent: :destroy
    has_many :quilters, through: :qals
    has_many :sponsors, through: :qals

    accepts_nested_attributes_for :qals
    accepts_nested_attributes_for :quilters
    accepts_nested_attributes_for :sponsors

      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, except: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if params[:user][:password] == params[:user][:password_confirmation] && @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            flash[:message] = "That was not a valid signup attempt. Please try again"
            redirect_to signup_path
        end
    end

    def show
        @user = current_user
        @qals = current_user.qals.all 
    end

    def edit
        @user = User.find_by(id: params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path
        else
            render :edit
        end
    end

    private

        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation, :company_name, :quilting_style)
        end

end

app/views/users/_user.html.erb
<div>
    <li>
        <%= link_to user.name, user %><br>
        <%= user.company_name %>  <br> 
    </li>
</div>

app/views/users/create.html.erb
<p>create a user </p>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<% provide(:button_text, 'Edit my Account') %>

<h1> Edit your Profile </h1>

    <div class="row">
        <div class="md-6 col-md-offset-3">

        <%= form_for(@user) do |f| %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %><br>
            
            <%= f.label :company_name %>
            <%= f.text_field :company_name, class: 'form-control' %><br>

            <%= f.label :quilting_style %>
            <%= f.text_field :quilting_style, class: 'form-control' %><br>

            <%= f.submit yield(:button_text), class: "btn btn-primary" %>

        <% end %>
            
        </div>
    </div>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<% provide(:button_text, 'Create my Account') %>

<h1>Sign up</h1>

<div class="row">
    <div class="md-6 col-md-offset-3">

        <%= form_for(@user) do |f| %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %><br>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %><br>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %><br>

            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %><br>

            <%= f.submit yield(:button_text), class: "btn btn-primary" %>

        <% end %>
        
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'User')%>

<h1> Hi, <%= @user.name %> </h1>

        <aside class="user-bio">
    
            <h4> Company Name:  </h4>
                <h5><%= @user.company_name %></h5><br>
            <h4> Quilting Style: </h4>
                <h5><%= @user.quilting_style %></h5><br>
            <h4> Number of Quilt-A-Longs: </h4>
                <h5><%= @user.qals.size %></h5><br>

             <% if current_user.id == @user.id %>
                    <p class="btn btn-sm"><%= link_to "Edit Profile ", edit_user_path(@user) %>
                <% end %></p>
        </aside>    

        <section class="user-qals">
            <h4>My Quilt-A-Longs</h4>
                <% @qals.each do |qal| %>
                <div class="user-qals-detail">
                    <%= link_to qal.qal_name, qal_path(qal) %><br>
                </div>
                    <% end %><br>
            <p class="btn btn-sm"><%= link_to "View All", qals_path %></p>
            <p class="btn btn-sm"><%= link_to "Add New", new_qal_path %></p>

        </section>


        







  
  

   

    