config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/faq', to: 'static_pages#faq'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  #sign up routes
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  #omniauth route
  match '/auth/:provider/callback', to: 'sessions#omniauth', via: [:get, :post]

    controller :sessions do
      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
  end

  get '/profile', to: 'users#show'
  get 'qals/finished_quilts', :to => 'qals#finished_quilts'
  get 'qals/beginners', :to => 'qals#good_for_beginners'
  get 'qals/ending_soon', :to => 'qals#ending_soon'

  resources :users, :only => [:create, :new, :show, :edit, :update]
  resources :qals 
  resources :quilts

#   nestiing new quilt form
  resources :quilters do 
    resources :quilts, :only => [:create, :index, :new]
  end

  resources :sponsors 
  resources :prizes
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord

    has_many :prizes, dependent: :destroy
    has_many :qals, through: :prizes

    accepts_nested_attributes_for :prizes
    accepts_nested_attributes_for :qals

    validates :sponsor_name, uniqueness: :true, presence: true

end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
    before_action :require_login

    def index
        @sponsors = Sponsor.all
        @qals = Qal.all #has many QALs through prizes
        @prizes = Prize.all  #has many prizes

    end

    def show
        @sponsor = Sponsor.find_by(id: params[:id])
    end

    def new
        @sponsor = Sponsor.new
    end

    def create
        @sponsor = Sponsor.create(sponsor_params)
        if @sponsor.save
            redirect_to sponsors_path
        else
            render :new
        end
    end

    def edit
        @sponsor = Sponsor.find_by(id: params[:id])
    end

    def update
        @sponsor = Sponsor.find_by(id: params[:id])
        @sponsor.update(sponsor_params)
        if @sponsor.save
            flash[:message] = "Successfully updated Sponsor."
        redirect_to sponsors_path
        else  
            render :edit
        end
    end

    def destroy
        @sponsor = Sponsor.find(params[:id])
        if @sponsor.delete
            flash[:message] = "Successfully deleted Sponsor."
        redirect_to sponsors_path
        else   
            render :edit  
        end
    end


    private 
        def sponsor_params
            params.require(:sponsor).permit(:sponsor_name)
        end
end

app/views/sponsors/_form.html.erb
<%= render partial: "layouts/errors", locals: {object: @sponsor} %>

<%= form_for (@sponsor) do |f| %>
<%= f.label :sponsor_name%>
<%= f.text_field :sponsor_name %>

<%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/sponsors/edit.html.erb
<% provide(:button_text, "Edit Sponsor") %>

<h2> Edit Sponsor <%= @sponsor.sponsor_name %></h2>

    <%= render 'form' %>

app/views/sponsors/index.html.erb
<h1> Sponsors </h1>

    <p class="btn btn-sm"><%= link_to "Add a Sponsor", new_sponsor_path %></p>
    <p class="btn btn-sm"><%= link_to "Add a Prize", new_prize_path %></p>

    <table class="table">
        <thead>
            <tr>
              <th> Name </th>
              <th> Quilt-A-Longs </th>
              <th> Prizes </th>
              <th>  </th>

             </tr>
        </thead>

        <tbody>
            <% @sponsors.each do |s| %>
            <tr>
                <td><%= s.sponsor_name %></td>

                <%# Sponsor has_many QALs through Prizes: %>
                <td>  
                    <p><% s.qals.each do |qal| %></p>
                    <%= qal.qal_name %>
                    <% end %>
                </td>
               
                <%# Sponsor has_many Prizes: %>
                 <td>
                     <p><% s.prizes.each do |prize| %></p>
                        <%= prize.prize_name %>
                     <% end %>
        
                </td>
                

                <td> 
                    <p class="btn btn-sm"><%= link_to "Edit", edit_sponsor_path(s) %></p>
                    <p class="btn btn-sm"><%= link_to "Delete", sponsor_path(s), method: :delete, data: { confirm: "Are you sure?" }  %></p>
                   
                </td>
            </tr>
              <% end %>
        </tbody>
    </table>



    

app/views/sponsors/new.html.erb
<% provide(:button_text, 'Create New Sponsor') %>

<%= render 'form' %>

app/views/sponsors/show.html.erb
<h3><%= @sponsor.sponsor_name %></h3>

<h4> <%= @sponsor.sponsor_name %> is a sponsor for these Quilt-A-Longs: </h4>




<p class="btn btn-sm"><%= link_to "Back to my profile", user_path %></p>

  