config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/faq', to: 'static_pages#faq'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  #sign up routes
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  #omniauth route
  match '/auth/:provider/callback', to: 'sessions#omniauth', via: [:get, :post]

    controller :sessions do
      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
  end

  get '/profile', to: 'users#show'
  get 'qals/finished_quilts', :to => 'qals#finished_quilts'
  get 'qals/beginners', :to => 'qals#good_for_beginners'
  get 'qals/ending_soon', :to => 'qals#ending_soon'

  resources :users, :only => [:create, :new, :show, :edit, :update]
  resources :qals 
  resources :quilts

#   nestiing new quilt form
  resources :quilters do 
    resources :quilts, :only => [:create, :index, :new]
  end

  resources :sponsors 
  resources :prizes
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <nav class="footer-nav">
    <small>
        Created by <a href="https://www.charliepops.com">Charlie-Pops-Studio</a>
    </small><br>
    <small>
        Quilt block by Studio Fibonacci from <a href="https://thenounproject.com">the Noun Project</a>
    </small>
        <ul>
            <li><%= link_to "FAQ", faq_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
    <div class="nav-container">
      <%= link_to "Quilt-A-Long",root_path, id: "logo" %><br>
    </div>

    <nav class="nav-header">
        <% if logged_in? %>
            <%= link_to "My Profile | ", '/profile' %>
            <%= link_to "Quilt-A-Longs | ", qals_path %>
            <%= link_to "Quilters | ", quilters_path %>
            <%= link_to "Sponsors | ", sponsors_path %>
            <%= link_to "Logout", logout_path, method: :delete %>   
        <% else %>
            <%= link_to "Signup", signup_path %>
            <%= link_to "Login", login_path %>

        <% end %>
    </nav>  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
        <title> <%= yield(:title) %> | Quilt-A-Long App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
   
    <!-- content -->

    <div class="container"  role="main">
      <div>
          <% if logged_in? %>
              <p class="logged-in-id"> Logged in as: <%= current_user.name %> </p>
              <% else %>
          <% end %>
      </div>

      <div>
        <% if flash[:message] %>
          <div class="warning"><%= flash[:message] %>
          <% end %>
        </div>

      <%= yield %>
      </div>
      
      <%= render 'layouts/footer' %>

  </body>
</html>